// frontend/src/components/ChatBox/ChatBox.tsx
import { useState, useEffect, useMemo, useRef, MutableRefObject } from 'react'
import { server_address } from '../../shared'
import { Radio, Checkbox } from 'antd';
import "./ChatBox.css"
import {
  UserOutlined,
  RobotOutlined
} from '@ant-design/icons';

type ChatgptMessage = {
  role: string
  content: string
}

function ChatBox({queryDocs}) {

  // const [query, setQuery] = useState<string>("")
  const inputBox: MutableRefObject<any> = useRef(null)
  const chatboxContent: MutableRefObject<any> = useRef(null)
  const [searchLoading, setSearchLoading] = useState<boolean>(false)
  const [usePrefix, setUsePrefix] = useState<boolean>(false)
  const [useSummary, setUseSummary] = useState<boolean>(true)
  const [messages, setMessages] = useState<Array<ChatgptMessage>>([])

  useEffect(() => {
    chatboxContent.current.scrollTop = chatboxContent.current.scrollHeight;
  }, [messages])

  useEffect(() => {
    if(queryDocs.length > 0) setUsePrefix(true)
    else setUsePrefix(false)
  }, [queryDocs])

  // const messages: MutableRefObject<Array<ChatgptMessage>> = useRef([{role: "system", content: "You are a chatbot used for text analysis."}])
  const queryOptions = [
    { label: 'Use Summary', value: true }, 
    { label: 'Use Full Content', value: false }
  ]


  function keyPressed(e) {
    if(e.code === "Enter"){
      e.preventDefault();
      let new_message: ChatgptMessage
      if(usePrefix) {
        new_message = {
          "role": "user",
          "content": `Given the selected documents, ` + e.target.textContent
        }
      } else {
        new_message = {
          "role": "user",
          "content": e.target.textContent
        }
      }
      const tmp_messages = [...messages, new_message]
      queryChatbot(tmp_messages)
      setMessages(tmp_messages)
      setUsePrefix(false)
      inputBox.current!.textContent = ""
      setSearchLoading(true)
    }
  }

  function queryChatbot(messages: Array<ChatgptMessage>) {
    const init_message: Array<ChatgptMessage> = [{role: "system", content: "You are a chatbot used for text analysis."}]
    const queryMessages = init_message.concat(messages)
    const useQueryDocs = usePrefix
    fetch(`${server_address}/static/chat`, {
      method: "POST",
      headers: {
          "Accept": "application/json",
          "Content-Type": "application/json"
      },
      body: JSON.stringify({ queryMessages, useQueryDocs, queryDocs, useSummary })
    })
    .then(res => res.json())
    .then(response => {
      console.log({response})
      const new_message = {
        "role": "system",
        "content": response
      }

      setSearchLoading(false)
      setMessages([...messages, new_message])
    })
  }

  

  return (
    <>
      <div className="chatbox-container flex flex-col h-full justify-between">
        <div className="chatbox-content basis-[70%] shrink overflow-y-auto" ref={chatboxContent}>
          <div className="chatbox-messages flex flex-col py-2">
            {
              messages.length === 0 &&
              <div className={ `chatbox-message w-fit mx-2 text-left flex items-top my-1`}> 
                <div className="inline text-2xl h-fit"> <UserOutlined/> </div>
                <div className="inline ml-2 border rounded p-2 w-[100px]"> { "" } </div>
              </div>
            }
            {
              messages.length > 0 &&
              messages.map((message, index) => (
                <div className={ `chatbox-message w-fit mx-2 text-left flex items-top my-1`} key={index}> 
                  <div className="inline text-2xl h-fit"> {message.role === "system"? <RobotOutlined /> : <UserOutlined/>} </div>
                  <div className="inline ml-2 border rounded p-2"> { message.content } </div>
                </div>
              ))
            }
            {
              searchLoading &&
              <div className={ `chatbox-message w-fit mx-2 text-left flex items-top my-1`} > 
                <div className="inline text-2xl h-fit">  <RobotOutlined /> </div>
                <div className="inline ml-2 border rounded p-2"> 
                  <span className='animate-[flash_2s_infinite]'>...</span>
                </div>
              </div>
            }
          </div>
        </div>
        <div className="lower-section basis-[30%] shrink-0 flex flex-col">
          <div className={`text-left mx-2 ${usePrefix? "":"line-through"}`}>Given the selected documents, <Checkbox checked={usePrefix} onChange={(e) => setUsePrefix(e.target.checked)}></Checkbox></div>
          <div className="input-container grow shrink-0 border-[1px] border-solid rounded overflow-y-auto mx-2 p-2 outline-none">
            <div className="
              text-region 
              break-all
              h-full 
              outline-none
              text-left"
              ref={inputBox}
              contentEditable={true}
              placeholder="input search text" 
              // onInput={onInput}
              // onChange={(e) => setQuery(e.target.value)}
              onKeyUp={keyPressed} 
              onKeyDown={(e) => { if(e.code === "Enter") e.preventDefault(); }}
              />
            </div>
            <div className="controller-container grow shrink-0 m-2 flex flex-col">
              <div className="query-doc-list grow flex flex-col content-between justify-between">
                <div className="text-left grow flex flex-col">
                  <div className="font-bold"> Selected Documents: </div>
                  <div className="grow border rounded p-1"> 
                    <ul className='list-disc list-inside'>
                      {queryDocs.map(doc => <li className="mr-2 inline" key={doc}> #{doc} </li>)}
                    </ul>
                  </div>
                </div>
              </div>
              <div className="flex items-center justify-between">
                <Radio.Group options={queryOptions} 
                  className="w-fit inline-block font-serif"
                  optionType='button'
                  buttonStyle='solid'
                  onChange={({target: {value}}) => setUseSummary(value)} value={useSummary} />
                <button className={"clear-chat btn ml-1 my-2 px-2 py-0 h-[32px] inline-block text-[14px] items-center"} onClick={() => setMessages([])}>Clear Chat</button>
              </div>
            </div>

        </div>
      </div>
    </>
  )
}
export default ChatBox

// frontend-svelte/src/lib/ChatBox.svelte
<script lang=ts>
    import UseSummaryRadio from "./UseSummaryRadio.svelte";
    const server_address = "http://localhost:5050"
    export let queryDocs;
    let searchLoading = false;
    let usePrefix = false;
    let useSummary = true;
    let messages: any[] = []
    let inputBox;
    let chatboxContent;


    // $: reposition_chatbox(messages)
    // function reposition_chatbox(_) {
    //     const chatbox_content = document.querySelector(".chatbox-content")
    //     if(chatbox_content) chatbox_content.scrollTop = chatbox_content.scrollHeight;
    // }
    $: usePrefix = queryDocs?.length > 0
    function keyPressed(e) {
        if(e.code === "Enter") {
            e.preventDefault();
            let new_message;
            if(usePrefix) {
                new_message = {
                "role": "user",
                "content": `Given the selected documents, ` + e.target.textContent
                }
            } else {
                new_message = {
                "role": "user",
                "content": e.target.textContent
                }
            }
            messages = [...messages, new_message]
            queryChatbot()
            usePrefix = false
            if(inputBox) inputBox.textContent = ""
            searchLoading = true
        }
    }

    function queryChatbot() {
        const init_message: any[] = [{role: "system", content: "You are a chatbot used for text analysis."}]
        const queryMessages = init_message.concat(messages)
        const useQueryDocs = usePrefix
        fetch(`${server_address}/static/chat`, {
            method: "POST",
            headers: {
                "Accept": "application/json",
                "Content-Type": "application/json"
            },
            body: JSON.stringify({ queryMessages, useQueryDocs, queryDocs, useSummary })
        })
        .then(res => res.json())
        .then(response => {
            console.log({response})
            const new_message = {
                "role": "system",
                "content": response
            }
            searchLoading = false
            messages = [...messages, new_message]
        })
    }
</script>
<div class="chatbox-container flex flex-col h-full justify-between">
    <div class="chatbox-content basis-[70%] shrink overflow-y-auto" bind:this={chatboxContent}>
        <div class="chatbox-messages flex flex-col py-2">
            {#if messages.length === 0}
                <div class={ `chatbox-message w-fit mx-2 text-left flex items-center my-1`}> 
                <div class="inline text-2xl h-fit"> <img class='icon' src='user.svg' alt='user'/> </div>
                <div class="inline ml-2 border rounded p-2 w-[100px]"> { "" } </div>
                </div>
            {:else}
                {#each messages as message, index}
                    <div class={ `chatbox-message w-fit mx-2 text-left flex items-center my-1`} > 
                        <div class="inline text-2xl h-fit"> 
                            {#if message.role === "system"}
                                <img class='icon' src='bot.svg' alt='bot' /> 
                            {:else}
                                <img class='icon'src='user.svg' alt='user'/>
                            {/if}
                        </div>
                        <div class="inline ml-2 border rounded p-2"> { message.content } </div>
                    </div>
                {/each}
            {/if}
            {#if searchLoading}
                <div class={ `chatbox-message w-fit mx-2 text-left flex items-center my-1`} > 
                <div class="inline text-2xl h-fit">  <img class='icon' src='bot.svg' alt='bot' /> </div>
                <div class="inline ml-2 border rounded p-2"> 
                    <span class='animate-[flash_2s_infinite]'>...</span>
                </div>
                </div>
            {/if}
        </div>
    </div>
    <div class="lower-section basis-[30%] shrink-0 flex flex-col shadow-inner border-solid rounded ">
        <div class={`text-left mx-2 ${usePrefix? "":"line-through"}`}>Given the selected documents, 
            <!-- <Checkbox checked={usePrefix} onChange={(e) => usePrefix = e.target.checked}></Checkbox> -->
            <input checked={usePrefix} on:change={() => usePrefix=!usePrefix} id="checked-checkbox" type="checkbox" value="" class="w-4 h-4 inline text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600">
            <!-- <label for="checked-checkbox" class="ml-2 text-sm font-medium text-gray-900 dark:text-gray-300">Checked state</label> -->
        </div>
        <div class="input-container grow shrink-0 border-[1px] border-solid rounded overflow-y-auto mx-2 p-2 outline-none ">
        <!-- svelte-ignore a11y-no-static-element-interactions -->
        <div class="
            input-box
            text-region 
            break-all
            h-full 
            outline-none
            text-left"
            bind:this={inputBox}
            contentEditable={true}
            placeholder="input search text" 
            on:keyup={keyPressed} 
            on:keydown={(e) => { if(e.code === "Enter") e.preventDefault(); }}
            />
        </div>
        <div class="controller-container grow shrink-0 m-2 flex flex-col">
            <div class="query-doc-list grow flex flex-col content-between justify-between">
            <div class="text-left grow flex flex-col">
                <div class="font-bold"> Selected Documents: </div>
                <div class="grow border rounded p-1"> 
                <ul class='list-disc list-inside'>
                    {#each queryDocs as doc}
                        <li class="mr-2 inline"> #{doc} </li>
                    {/each}
                </ul>
                </div>
            </div>
            </div>
            <div class="flex items-center justify-between">
                <div class='w-fit basis-[70%] mt-1 inline-block font-serit'>
                    <UseSummaryRadio bind:useSummary={useSummary} />
                </div>
                <button class={"clear-chat btn ml-1 mt-1 px-2 h-full py-0 h-[32px] inline-block text-[14px] items-center"} on:click={() => messages=[]}>Clear Chat</button>
            </div>
        </div>
    </div>
</div>

<style>
    .icon {
        width: 28px;
        height: 28px;
    }
</style>
