// frontend/src/components/DocList/DocList.tsx
import { useState, useEffect, useMemo, useRef } from 'react'
import DocCard from '../DocCard/DocCard'
import type { tDocument } from '../../types/Doc'
type DocListProps = {
  docs: Array<tDocument>
  cluster_label: string
  theme: string
}
function DocList({docs, cluster_label, theme}: DocListProps) {
  const setOpacity = (hex, alpha) => `${hex}${Math.floor(alpha * 255).toString(16).padStart(2, '0')}`;
  const themeColor = useMemo(() => setOpacity(theme, 0.5), [theme])
  console.log(themeColor, cluster_label)
  return (
    <>
      <div className="doc-list-container px-2">
        <div className='doc-list-header px-2 flex rounded items-center w-full justify-center' style={{background: themeColor}}>
          {/* <svg className="inline" width='20' height='20'><rect width='20' height='20' fill={themeColor}></rect></svg> */}
          <p className="cluster-label font-serif text-2xl w-fit" >{ cluster_label }</p>
        </div>
        <div className="doc-list-content">
          {
            docs.map((doc, index) => ( <DocCard doc={doc} index={index} theme={theme}></DocCard> ))
          }
        </div>
      </div>
    </>
  )
}

export default DocList

// frontend-baseline/src/lib/DocList.svelte
<script lang="ts">
  import { createEventDispatcher } from "svelte";
  import DocCard from "./DocCard.svelte";
  const dispatch = createEventDispatcher();
  export let docs;
  export let clickedDocs;

  function handleCardClicked(event) {
    console.log(event.detail);
    const { id, add, title } = event.detail;
    if (add) {
      clickedDocs = [...clickedDocs, { id, title }];
    } else {
      clickedDocs = clickedDocs.filter((doc) => doc.id !== id);
    }
  }
</script>

<div class="doc-list-container px-2 w-full h-full flex flex-col">
  <div
    class="doc-list-header px-2 flex rounded items-center w-full justify-center"
  >
    <p class="cluster-label font-serif text-2xl w-fit">Document List</p>
  </div>
  <div class="grow overflow-y-scroll">
    <div class="doc-list-content">
      {#each docs as doc}
        <DocCard {doc} on:click={handleCardClicked} />
      {/each}
    </div>
  </div>
</div>
