// frontend-svelte/src/lib/DocList.svelte
<script lang=ts>
    import { createEventDispatcher } from "svelte";
    import DocCard from "./DocCard.svelte";
    const dispatch = createEventDispatcher();
    export let docs;
    export let cluster_label;
    export let theme;
    export let highlightDocs;
    export let clickedDocs;

    $: themeColor = getThemeColor(theme)
    $: highlightDocIds = highlightDocs?.map(doc => doc.id)
    $: highlightedDocs = (() => {
        console.log(docs)
        if(!docs) return [{ id: "1", title: "", summary: ""}, { id: "2", title: "", summary: ""}]
        // add highlight flag
        docs.forEach(doc => {
        if(highlightDocIds === undefined) {
            doc.highlight = true;
            return
        }
        if(highlightDocIds.length === 0) {
            doc.highlight = false;
            return
        }
        if(highlightDocIds.includes(doc.id)) {
            doc.highlight = true;
        }
        })
        // sort by relevance
        if(highlightDocs && highlightDocs.length > 0) {
            docs.sort((a, b) => b.relevance! - a.relevance!)
        }
        return docs
    })()

    function handleCardClicked(event) {
        console.log(event.detail)
        const {doc_id, add} = event.detail
        if(add) {
            clickedDocs = [...clickedDocs, doc_id]
        } else {
            clickedDocs = clickedDocs.filter(id => id !== doc_id)
        }
    }
    function setOpacity(hex, alpha) {
        return `${hex}${Math.floor(alpha * 255).toString(16).padStart(2, '0')}`
    }
    function getThemeColor(theme) {
        return theme? setOpacity(theme, 0.5) : "unset"
    }
</script>
<div class="doc-list-container px-2">
    <div class='doc-list-header px-2 flex rounded items-center w-full justify-center' style={`background: ${themeColor}`}>
        <p class="cluster-label font-serif text-2xl w-fit" >{ cluster_label }</p>
    </div>
    <div class="doc-list-content">
        {#each highlightedDocs as doc}
            <DocCard doc={doc}  on:click={handleCardClicked}></DocCard>
        {/each}
    </div>
</div>

// frontend-deprecated/src/components/DocList/DocList.tsx
import { useState, useEffect, useMemo, useRef, MutableRefObject } from 'react'
import DocCard from '../DocCard/DocCard'
import type { tDocument } from '../../types/Doc'
type DocListProps = {
  docs: Array<tDocument> | undefined
  cluster_label: string
  theme: string
  highlightDocs: Array<any> | undefined
  onQueryDocChanged: (doc_ids: Array<string>) => void
}
function DocList({docs, cluster_label, theme, highlightDocs, onQueryDocChanged}: DocListProps) {
  const setOpacity = (hex, alpha) => `${hex}${Math.floor(alpha * 255).toString(16).padStart(2, '0')}`;
  const themeColor = useMemo(() =>  theme? setOpacity(theme, 0.5): "unset", [theme])
  const highlightDocIds = useMemo(() => highlightDocs?.map(doc => doc.id), [highlightDocs])
  const highlightedDocs = useMemo(() => {
    if(!docs) return [{ id: "1", title: "", summary: ""}, { id: "2", title: "", summary: ""}]
    // add highlight flag
    docs.forEach(doc => {
      if(highlightDocIds === undefined) {
        doc.highlight = true;
        return
      }
      if(highlightDocIds.length === 0) {
        doc.highlight = false;
        return
      }
      if(highlightDocIds.includes(doc.id)) {
        doc.highlight = true;
      }
    })
    // sort by relevance
    if(highlightDocs && highlightDocs.length > 0) {
      docs.sort((a, b) => b.relevance! - a.relevance!)
    }
    console.log(docs)
    return docs
  }, [docs, highlightDocs])

  const clickedDocs: MutableRefObject<Array<string>> = useRef([])
  const handleCardClicked = (doc_id: string, add: boolean) => {
    if(add) {
      clickedDocs.current.push(doc_id)
    } else {
      clickedDocs.current = clickedDocs.current.filter(id => id !== doc_id)
    }
    // somehow deep copy is needed here
    onQueryDocChanged(JSON.parse(JSON.stringify(clickedDocs.current)))
  }
  return (
    <>
      <div className="doc-list-container px-2">
        <div className='doc-list-header px-2 flex rounded items-center w-full justify-center' style={{background: themeColor}}>
          {/* <svg className="inline" width='20' height='20'><rect width='20' height='20' fill={themeColor}></rect></svg> */}
          <p className="cluster-label font-serif text-2xl w-fit" >{ cluster_label }</p>
        </div>
        <div className="doc-list-content">
          {
            highlightedDocs.map((doc, index) => ( <DocCard doc={doc} index={index} key={doc.id} handleCardClicked={handleCardClicked}></DocCard> ))
          }
        </div>
      </div>
    </>
  )
}

export default DocList
